# Example configuration file demonstrating theme color overrides
# This file shows how to customize the appearance of any theme without creating a full theme file

[ui]
# Use the gruvbox-dark theme as the base
theme = "gruvbox-dark"

# Theme color overrides
# These will be applied on top of the base theme
[ui.theme_overrides]
# Make the background pure black for a more minimal look
background = "#000000"

# Change text color to a lighter shade for better readability
text_fg = "#e8e8e8"

# Make selection background more visible
selection_bg = "#444444"

# Highlight matches in bright red for better visibility
match_fg = "#ff0000"

# Customize input text color
input_text_fg = "#ff6b6b"

# Make result names stand out more
result_name_fg = "#74c0fc"

# Customize preview title color
preview_title_fg = "#ffd93d"

# Example of using ANSI color names instead of hex values
# border_fg = "bright-white"
# dimmed_text_fg = "bright-black"
# channel_mode_bg = "green"
# remote_control_mode_bg = "yellow"

# Other UI settings
ui_scale = 100
input_bar_position = "top"
orientation = "landscape"

# UI Features
[ui.features]
preview_panel = { enabled = true, visible = true }
help_panel = { enabled = true, visible = false }
status_bar = { enabled = true, visible = true }
remote_control = { enabled = true, visible = false }

# General settings
tick_rate = 50
default_channel = "files"
history_size = 200
global_history = false 