[theme]
background = '#2c2c2c'
foreground = '#d6d6d6'
black   = '#1c1c1c'
red     = '#bc5653'
green   = '#909d63'
yellow  = '#ebc17a'
blue    = '#7eaac7'
magenta = '#aa6292'
cyan    = '#86d3ce'
white   = '#cacaca'
bright_black   = '#636363'
bright_red     = '#bc5653'
bright_green   = '#909d63'
bright_yellow  = '#ebc17a'
bright_blue    = '#7eaac7'
bright_magenta = '#aa6292'
bright_cyan    = '#86d3ce'
bright_white   = '#f7f7f7'
