[theme]
background = '#0A0E14'
foreground = '#B3B1AD'
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'
bright_black   = '#686868'
bright_red     = '#F07178'
bright_green   = '#C2D94C'
bright_yellow  = '#FFB454'
bright_blue    = '#59C2FF'
bright_magenta = '#FFEE99'
bright_cyan    = '#95E6CB'
bright_white   = '#FFFFFF'
