[theme]
background = '#1E1E2E'
foreground = '#D6D6D6'
black = '#181A1F'
red = '#E86671'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#C678DD'
cyan = '#54AFBC'
white = '#ABB2BF'
bright_black = '#5C6370'
bright_red = '#E86671'
bright_green = '#98C379'
bright_yellow = '#E5C07B'
bright_blue = '#61AFEF'
bright_magenta = '#C678DD'
bright_cyan = '#54AFBC'
bright_white = '#F7F7F7'
