[theme]
background = '#2E3440'
foreground = '#D8DEE9'
black   = '#3B4252'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#88C0D0'
white   = '#E5E9F0'
bright_black   = '#4C566A'
bright_red     = '#BF616A'
bright_green   = '#A3BE8C'
bright_yellow  = '#EBCB8B'
bright_blue    = '#81A1C1'
bright_magenta = '#B48EAD'
bright_cyan    = '#8FBCBB'
bright_white   = '#ECEFF4'
