[metadata]
name = "dirs"
description = "A channel to select from directories"
requirements = ["fd"]

[source]
command = ["fd -t d .", "fd -t d --hidden ."]
transition = ["text", "files"]

[preview]
command = "ls -la --color=always {}"
