[metadata]
name = "dirs"
description = "A channel to select from directories"
requirements = ["fd"]

[source]
command = ["fd -t d .", "fd -t d --hidden ."]

[preview]
command = "ls -la --color=always {}"

[transition]
# remove trailing /
files = ". {replace:s/\\/$//g}"
# use extra command flag on top of the arguments
text = "--with-filename {}"
pepe = "{}"