[metadata]
name = "dirs"
description = "A channel to select from directories"
requirements = [["fd", "fdfind"]]

[source]
command = [
  { name = "Default", run = "$(command -v fd || echo fdfind) -t d" },
  { name = "Hidden",  run = "$(command -v fd || echo fdfind) -t d --hidden" },
]

[preview]
command = "ls -la --color=always '{}'"

[keybindings]
shortcut = "f2"

[actions.cd]
description = "Open a shell in the selected directory"
command = "cd {} && $SHELL"
mode = "execute"

[actions.goto_parent_dir]
description = "Re-opens tv in the parent directory"
command = "tv dirs .."
mode = "execute"
