[metadata]
name = "dotfiles"
description = "A channel to select from your user's dotfiles"
requirements = [["fd", "fdfind"], "bat"]

[source]
command = "$(command -v fd || echo fdfind) -t f . $HOME/.config"

[preview]
command = "bat -n --color=always '{}'"

[keybindings]
shift-enter = "actions:edit"

[actions.edit]
description = "Edit the selected dotfile"
command = "${EDITOR:-vim} {}"
shell = "bash"
mode = "execute"
