[metadata]
name = "git-reflog"
description = "A channel to select from git reflog entries"

[source]
command = "git reflog"
output = "{split: :0}"

[preview]
command = "git show -p --stat --pretty=fuller --color=always {0}"
