[metadata]
name = "path"
description = "Investigate PATH contents"
requirements = [["fd", "fdfind"], ["bat", "batcat"]]

[source]
command = "printf '%s\n' \"$PATH\" | tr ':' '\n'"

[preview]
command = "$(command -v fd || echo fdfind) -tx -d1 . \"{}\" -X printf \"%s\n\" \"{/}\" | sort -f | $(command -v bat || echo batcat) -n --color=always"

[actions.cd]
description = "Open a shell in the selected PATH directory"
command = "cd {} && $SHELL"
mode = "execute"
