name: Publish to WinGet
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Specific tag name'
        required: true
        type: string
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@4ffc7888bffd451b357355dc214d43bb9f23917e # v2
        with:
          identifier: 'alexpasmantier.television'
          installers-regex: '-windows-x86_64\.zip$'
          max-versions-to-keep: 5
          token: ${{ secrets.PAT_FOR_WINGET_RELEASER }}
